# Create a config/odata.yml file based on this sample file
test:
  data_url: 'https://mycompany.com/TEST/api/data/v8.1/'
  old_data_url: 'https://mycompany.com/TEST/XRMServices/2011/OrganizationData.svc/'
  username: test_username
  password: test_user_password
